<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio | Keefe</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

# Exercise 1

- Subsetting = to select a part of a list
- Indexing = to select a specific value from a list
- Slicing = to select a range of values from a list
- Masking = to show only those values from the list which meet the requirement you set


# Exercise 2

In [3]:
import numpy as np

In [4]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

In [21]:
first_numbers = np_array_2d[:,0]

In [18]:
print(first_numbers)

['1' '3' '2' '4' '5' '7' '6' '8' '10' '9']


In [28]:
first_numbers = first_numbers.astype(int)

In [29]:
first_numbers

array([ 1,  3,  2,  4,  5,  7,  6,  8, 10,  9])

In [33]:
remainder = first_numbers%2

remainder

array([1, 1, 0, 0, 1, 1, 0, 0, 0, 1])

In [39]:
True_count = remainder > 0

True_count

array([ True,  True, False, False,  True,  True, False, False, False,
        True])

In [42]:
np_array_2d[True_count, 1]

array(['A', 'C', 'E', 'G', 'I'], dtype='<U21')