<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

# What to expect in this chapter

# 1 Lists, Arrays & Dictionaries

In [2]:
import numpy as np

## 1.1 Let’s compare

In [4]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

#the above are python LISTS.

In [6]:
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

#the above are numpy ARRAYS.

In [7]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}

#the above is a dictionary

## 1.2 Accessing data from a list (or array)

In [9]:
py_real_names[0] #note that the first item in the list has the position '0', not 1.

'Natasha Romanoff'

In [10]:
py_super_names[0]

'Black Widow'

In [12]:
py_super_names[-1]   
# Reverse indexing: getting it from the back instead. 
#Notice for counting from the back, it's -1 as the last item, not -0

'Doctor Strange'

## 1.3 Accessing data from a dictionary

In [15]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}                  

#Remember that dictionaries have a key-value structure.

In [16]:
superhero_info["Natasha Romanoff"]

'Black Widow'

In [18]:
superhero_info.keys()
#this accesses all keys (the 'word')

dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange'])

In [ ]:
superhero_info.values()
#this accesses all values (the 'meaning')

## 1.4 Higher dimensional lists

In [19]:
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]

#this is a 2D list, it has lists within a big list. 
#This is to overcome the fact that lists dont have the key-value function of dictionaries

# 2 Lists vs. Arrays

In [20]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array

## 2.1 Size

In [34]:
len(py_list_2d)
#use len() to get the length of something, in this case how many items in list.

10

In [39]:
len(np_array_2d)

#can use len() on arrays to get its length too

10

In [38]:
np_array_2d.shape
#use .shape to get these stats on an array: (1) its lenghth (2) its dimensionality

(10, 2)

## 2.2 Arrays are fussy about type

In [40]:
py_list = [1, 1.5, 'A']
np_array = np.array(py_list)

In [41]:
py_list

[1, 1.5, 'A']

In [44]:
np_array

#notice that calling this will always give the type of data at the end
#in this case <U32 unicode means it's the type: String.

array(['1', '1.5', 'A'], dtype='<U32')

## 2.3 Adding a number

In [45]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         # Reusing the Python list
                                     # to create a NEW
                                     # NumPy array

In [46]:
np_array + 10

#can add a number to all values in an array^
#but this wont work for python lists.

array([11, 12, 13, 14, 15])

## 2.4 Adding another list

In [47]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

In [49]:
py_list_1 + py_list_2

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [51]:
#notice that adding a list to another will simply combine them into a longer list

In [50]:
np_array_1 + np_array_2

array([11, 22, 33, 44, 55])

In [52]:
#notice that adding an array to another adds up each of the numbers

## 2.5 Multiplying by a Number

In [53]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [62]:
py_list*2

#multiplying a list doubles it (repeats it)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [60]:
np_array*2

#multiplying array will multiply each of the numbers inside.

array([ 2,  4,  6,  8, 10])

## 2.6 Squaring

In [63]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

In [65]:
np_array**2
#squaring works for arrays

array([ 1,  4,  9, 16, 25])

In [66]:
py_list**2                      # Won't work!  

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

## 2.7 Asking questions

In [67]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [70]:
py_list == 3     #this asks whether this variable is the integer 3. It's not, it's a list

False

In [71]:
np_array == 3  #this asks whether each value in the array is equal to 3.

array([False, False,  True, False, False])

In [73]:
np_array > 3  #this asks whether each value in the array is greater than 3.

array([False, False, False,  True,  True])

## 2.8 Mathematics

In [74]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [76]:
sum(py_list)     # sum() is a base Python function

15

In [78]:
max(py_list)     # max() is a base Python function

5

In [82]:
min(py_list)     # min() is a base Python function


1

In [83]:
np_array.sum()


15

In [84]:
np_array.max()


5

In [85]:
np_array.min()

1

In [86]:
np_array.mean()

3.0

In [87]:
np_array.std()


1.4142135623730951

# Exercises & Self-Assessment

In [ ]:



# Your solution here




## Footnotes