<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

# What to expect in this chapter

# 1 Subsetting: Indexing and Slicing

- Subsetting means to ‘select’.
- Indexing refers to selecting one element. (like when print(list[4]))
- Slicing refers to selecting a range of elements. 

## 1.1 Lists & Arrays in 1D | Subsetting & Indexing

In [8]:
import numpy as np

In [7]:
py_list = ["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]

x = py_list


In [9]:
x[0]

'a1'

In [11]:
x[0:3]   #this gives index 0 to 2. 0, 1, 2 (but not 3)

['a1', 'b2', 'c3']

In [12]:
x[1:6]    #this gives index 1, 2, 3, 4, 5

['b2', 'c3', 'd4', 'e5', 'f6']

In [14]:
x[1:6:2]    #this gives from 1 to 5, starts from 1, but in steps of 2. So 1, 3, 5.

['b2', 'd4', 'f6']

In [16]:
x[5:]    #index 5 to the end

['f6', 'g7', 'h8', 'i9', 'j10']

In [20]:
x[:4]    #from start till index 3 (the second number of the [:4] is always not inclusive)

['a1', 'b2', 'c3', 'd4']

In [37]:
x[5:2]
#doesn't work, just gives you a blank list. See below for how to make it work
#because the default is to read fwd

[]

In [32]:
x[5:2:-1]  
#from index 5 to 3, in reverse. tells it to read backwards
#the -1 reverses the list

['f6', 'e5', 'd4']

In [36]:
x[2:5:-1]
#want it to read forwards but then -1 confuses it to read backwards, doesnt work

[]

In [31]:
x[::-1] 
#gives you the list in reverse
#I read it as: give from start to end, but in reverse

['j10', 'i9', 'h8', 'g7', 'f6', 'e5', 'd4', 'c3', 'b2', 'a1']

## 1.2 Arrays only | Subsetting by masking

In [41]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3

print(my_mask)

np_array[my_mask]
#this shows me all the values which are true to be >3

[False False False  True  True  True  True  True  True  True]


array([ 4,  5,  6,  7,  8,  9, 10])

In [43]:
#here's a more concise way to do the above:

np_array[np_array > 3] #means from the np_array, only show those values which >3

array([ 4,  5,  6,  7,  8,  9, 10])

In [46]:
np_array[~(np_array > 3)]                 
# '~' means 'NOT'
# so now i get all the values 3 and below from the array


array([1, 2, 3])

In [47]:
np_array[(np_array > 3) & (np_array < 8)] # '&' means 'AND'

array([4, 5, 6, 7])

In [49]:
np_array[(np_array < 3) | (np_array > 8)] # '|' means 'OR'

array([ 1,  2,  9, 10])

In [56]:
np_array[(np_array < 3) | ~(np_array > 5)] 
# '|' means 'OR'
#this means print everything below 3 + print everything not above 5 (but doesnt repeat values)

array([1, 2, 3, 4, 5])

In [57]:
np_array[(np_array < 3) & ~(np_array > 5)] 
# '|' means 'OR'
# now i only get 1 and 2 coz it has to satisfy both sides

array([1, 2])

## 1.3 Lists & Arrays in 2D | Indexing & Slicing

In [58]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)

In [60]:
py_list_2d[3]
#what is the list at position 4

[4, 'D']

In [62]:
py_list_2d[3][0]
#what is the first item in the list at position 4

4

In [63]:
np_array_2d[3]
#what is the list at position 4

array(['4', 'D'], dtype='<U21')

In [75]:
np_array_2d[3, 0]
#what is the first item in the list at position 4
#notice that if its an array, just use 1 [], separate numbers with ,

'4'

In [70]:
py_list_2d[:3]
#what are the lists from start till position 2 (inclusive)

[[1, 'A'], [2, 'B'], [3, 'C']]

In [74]:
py_list_2d[:3][0]
#what are the lists from start till position 2 (inclusive)?
#then give me just the item in position 0.

[1, 'A']

In [71]:
np_array_2d[:3]
#what are the lists from start till position 2 (inclusive)

array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C']], dtype='<U21')

In [73]:
np_array_2d[:3, 0]
#what are the lists from start till position 2 (inclusive)?
#then give me the first item IN EACH of the lists.

array(['1', '2', '3'], dtype='<U21')

In [76]:
py_list_2d[3:6][0]
#Get position 3, 4, 5. what's the 1st item in this new list?

[4, 'D']

In [79]:
np_array_2d[3:6, 0]
#Get position 3, 4, 5. What's the 1st item in each of the lists retrieved?

array(['4', '5', '6'], dtype='<U21')

In [80]:
np_array_2d[:, 0]
#Get positions from start to end (everything). What's the 1st item in each of the lists retrieved?

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U21')

## 1.4 Growing lists

`3 different ways to grow lists (adding 1 element at a time)`

In [81]:
x=[1]
x= x + [2]
x= x + [3]
x= x + [4]
x

[1, 2, 3, 4]

In [82]:
x=[1]
x+= [2]
x+= [3]
x+= [4]
x

[1, 2, 3, 4]

In [84]:
x=[1]
x.append(2)
x.append(3)
x.append(4)
x

#the execution spd of this is fastest

[1, 2, 3, 4]

`3 diff ways to extend lists (add mulitple elements at once)`

In [85]:
x = [1, 2, 3]
x += [4, 5, 6]
x

[1, 2, 3, 4, 5, 6]

In [86]:
x=[1, 2, 3]
x.extend([4, 5, 6])
x

[1, 2, 3, 4, 5, 6]

In [88]:
x=[1, 2, 3]
x.append([4, 5, 6])
x

#NOTICE this appends a new list within the first list. The list [4,5,6] is seen as 1 'item'

[1, 2, 3, [4, 5, 6]]

# Some loose ends

## 1.5 Tuples

In [94]:
a = (1, 2, 3)     # Define tuple
#note that tuples are immutable, i.e. can't be changed

In [90]:
print(a[0])    # Access data

1


In [93]:
# The following will NOT work
a[0]=-1
# the above means to change the first item in tuple a to the integer -1
a[0]+= [10]

TypeError: 'tuple' object does not support item assignment

## 1.6 Be VERY careful when copying

In [126]:
x=[1, 2, 3]
y=x           # DON'T do this!
z=x           # DON'T do this!

#it might screw up code later on.

In [121]:
x=[1, 2, 3]
y=x.copy()
z=x.copy()

In [122]:
y

[1, 2, 3]

In [123]:
z

[1, 2, 3]

# Exercises & Self-Assessment

In [ ]:



# Your solution here




## Footnotes